# Numpy


Source: These notes are build on Udacity's Data Analyst Nanodegree.

NumPy stands for Numerical Python. It is a key package for every data analyst and scientific computing in Python. Essentially it provides a massive math library. 


In [20]:
!conda list numpy


# packages in environment at C:\Users\Philipp\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.14.3           py36h9fa60d3_1  
numpy-base                1.14.3           py36h555522e_1  
numpydoc                  0.8.0                    py36_0  


In [21]:
conda install
numpy=1.13

SyntaxError: invalid syntax (<ipython-input-21-0ef92f1d98b9>, line 1)

NumPy is built on C, which is a lower level language. So it brings speed. 

Also it has its core multidimensional arrays.
NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.

It's built-in mathematical functions make your code lean. 



## ndarrays

This stands for n dimensional array.

There are several ways to create ndarrays in NumPy. In the following lessons we will see two ways to create ndarrays:

1. Using regular Python lists

2. Using built-in NumPy functions

In [22]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(x)
print() 
print(type(x))

[1 2 3 4]

<class 'numpy.ndarray'>


In [23]:
print(x)
print(type(x)) #this is the datatype of the array itself
x.dtype #this is the datatype of the elements within the array, it must all be the same

[1 2 3 4]
<class 'numpy.ndarray'>


dtype('int32')

Let's pause for a second to introduce some useful terminology. 
We refer to 1D arrays as rank 1 arrays. In general N-Dimensional arrays have rank N. 

Another important property of arrays is their shape. The shape of an array is the size along each of its dimensions. For example, the shape of a rank 2 array will correspond to the number of rows and columns of the array. 

NumPy ndarrays have attributes that allows us to get information about them in a very intuitive way. For example, the shape of an ndarray can be obtained using the .shape attribute. The shape attribute returns a tuple of N positive integers that specify the sizes of each dimension. 

In [24]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 


x =  [1 2 3 4 5]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [25]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print x
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 
#the .dtype attribute tells us that the elements in x are stored in memory as Unicode strings of 5 characters, see result below


x =  ['Hello' 'World']

x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


It is important to remember that one big difference between Python lists and ndarrays, is that unlike Python lists, all the elements of an ndarray must be of the same type. So, while we can create Python lists with both integers and strings, we can't mix types in ndarrays. If you provide the np.array() function with a Python list that has both integers and strings, NumPy will interpret all elements as strings. 


In [26]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


In [27]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)



Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


In [28]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


In [29]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int64


When loading an array from a file, make sure you include the name of the file together with the extension .npy, 
otherwise you will get an error.



In [30]:
list = ([1 ,2 ,3])
np.array(list)
print(list)

[1, 2, 3]


### Using built-in functions to create arrays


Let's start by creating an ndarray with a specified shape that is full of zeros. We can do this by using the np.zeros() function. The function np.zeros(shape) creates an ndarray full of zeros with the given shape. So, for example, if you wanted to create a rank 2 array with 3 rows and 4 columns, you will pass the shape to the function in the form of (rows, columns), 

In [31]:
x = np.zeros((3,4))
print(x)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
# we can change the datatype
x = np.zeros((3,4), dtype = int)
print(x)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [33]:
x = np.ones((2,3))
print(x)


[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
x = np.full((2,3), 5)
print(x)


[[5 5 5]
 [5 5 5]]


In [35]:
x = np.eye(5)

In [36]:
np.diag((10,20,30))
print(x)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
x = np.arange(4,10) #endpoint exclusive
print(x)


[4 5 6 7 8 9]


In [38]:
x = np.arange(4,10,2)
print(x)


[4 6 8]


In [39]:
x = np.linspace(1,10,40) #with incluse start and end point
print(x)


[ 1.          1.23076923  1.46153846  1.69230769  1.92307692  2.15384615
  2.38461538  2.61538462  2.84615385  3.07692308  3.30769231  3.53846154
  3.76923077  4.          4.23076923  4.46153846  4.69230769  4.92307692
  5.15384615  5.38461538  5.61538462  5.84615385  6.07692308  6.30769231
  6.53846154  6.76923077  7.          7.23076923  7.46153846  7.69230769
  7.92307692  8.15384615  8.38461538  8.61538462  8.84615385  9.07692308
  9.30769231  9.53846154  9.76923077 10.        ]


In [40]:
x = np.array([1,2,3,4])
x = np.reshape(x,(2,2)) #specified of shape needs to be compatible with number of elements in the list
print(x)

[[1 2]
 [3 4]]


In [41]:
# It is helpful that some functions in numpy can be applied as methods.
# This allows us to apply a sequence of operations in just one line of code.
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [42]:
x = np.linspace(0, 50, 10, endpoint = False).reshape(5,2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [43]:
#now we want to access random function which are in the random module
# so we type random.name_of_function to access those
x = np.random.random((3,3))
print(x)

[[0.40977899 0.92131368 0.32904328]
 [0.52854244 0.36156555 0.45498017]
 [0.60698965 0.35926237 0.88678033]]


In [44]:
x = np.random.randint(5, 101, (2, 2))
print(x)

[[52 69]
 [ 5 94]]


In [45]:
# now with random numbers that satisfy certain statistical properties
# modelling equity here with a mean of 5% and a vol of 20%
x = np.random.normal(0.05, 0.2, size=(1000, 1000))
print(x)

print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in X are of type:', x.dtype)
print('The elements in X have a mean of:', x.mean())
print('The maximum value in X is:', x.max())
print('The minimum value in X is:', x.min())
print('X has', (x < 0).sum(), 'negative numbers')
print('X has', (x > 0).sum(), 'positive numbers')


[[-0.42977368  0.15069917  0.22651295 ...  0.2112953   0.25439325
   0.2148699 ]
 [-0.06287219  0.22009092  0.49849062 ...  0.09933882 -0.23403213
  -0.02226113]
 [-0.00486318  0.19571931  0.13064713 ...  0.09352449 -0.30091422
   0.22707663]
 ...
 [-0.32987973  0.02287677  0.33457658 ...  0.16599722  0.46205289
   0.15991406]
 [-0.16836563 -0.05480417  0.01226746 ...  0.44896721 -0.24910647
   0.35841893]
 [ 0.25256459  0.02586074 -0.0374502  ... -0.12462487  0.14589517
  -0.11048173]]
X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 0.05007698072900978
The maximum value in X is: 1.0655504599504124
The minimum value in X is: -0.9668071723822096
X has 401322 negative numbers
X has 598678 positive numbers


### Manipulating data within the arrays

Arrays are mutable, meaning we can change the data in the arrays after they have been created.

Often we slice datasets, essentially separating them.
For example into training, cross validation and testing data sets.

We can access elements by using indices in []


In [46]:
x = np.array([1, 2, 3])
print('First element', x[0])
print('Last element', x[-1])

First element 1
Last element 3


In [47]:
# and now we modify the element
x[-1] = 100
print(x)

[  1   2 100]


In [48]:
# now we work with a 3D i.e. rank 3 array
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# Row, Column
print('Element in 2nd row, 3rd column: ', x[1,2])

Element in 2nd row, 3rd column:  6


In [50]:
x[2,2] = 20
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 20]]


In [51]:
# delete elements

# for that we create a rank 1 array
x = np.array([1, 2, 3, 4, 5, ])
print('x = ', x)
print() 

# and we create a rank 2 array 
y = np.array([[1, 2,], [3, 4], [5, 6]])
print('y = ', y)
print() 

x = np.delete(x, [0, 4])
print('Modified x = ', x)
print() 

y = np.delete(y, [0], axis = 0) #axis 0 is used to select rows, i.e. this is the first row
print('Modified y = ', y) 
print() 
y =  np.delete(y, [1], axis = 1) #axis 1 is used to select columns, i.e. this is the second column
print('Modified y = ', y)

# we can use the append function to add elements to an array.
# the syntax for that is just like the delete funtion

x =  [1 2 3 4 5]

y =  [[1 2]
 [3 4]
 [5 6]]

Modified x =  [2 3 4]

Modified y =  [[3 4]
 [5 6]]

Modified y =  [[3]
 [5]]


In [52]:
# we can use the append function to add elements to an array.
# the syntax for that is just like the delete funtion
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


In [53]:
# we can also insert elements into an array
# We can insert values to ndarrays using the np.insert(ndarray, index, elements, axis) function. 
# This function inserts the given list of elements to ndarray right before the given index along the specified axis. 


# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


In [54]:
#NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side. 
#The stacking is done using either the np.vstack() function for vertical stacking, or the np.hstack() function for horizontal stacking. 
#It is important to note that in order to stack ndarrays, the shape of the ndarrays must match.

# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)




x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


### Slicing
As we mentioned earlier, in addition to being able to access individual elements one at a time, NumPy provides a way to access subsets of ndarrays. This is known as slicing. Slicing is performed by combining indices with the colon : symbol inside the square brackets. In general you will come across three types of slicing:

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]
The first method is used to select elements between the start and end indices. The second method is used to select all elements from the start index till the last index. The third method is used to select all elements from the first index till the end index. We should note that in methods one and three, the end index is excluded. We should also note that since ndarrays can be multidimensional, when doing slicing you usually have to specify a slice for each dimension of the array.

We will now see some examples of how to use the above methods to select different subsets of a rank 2 ndarray.

In [55]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)

# Remember: slicing only creates a view of the original array. 
# This means that if you make changes in Z you will be in effect changing the elements in X as well.


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


### Copying

if we want to create a new ndarray that contains a copy of the values in the slice we need to use the np.copy() function. The np.copy(ndarray) function creates a copy of the given ndarray. 
This function can also be used as a method, in the same way as we did before with the reshape function. 
Let's do the same example we did before but now with copies of the arrays. We'll use copy both as a function and as a method

In [57]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)

# We can clearly see that by using the copy command, 
# we are creating new ndarrays that are completely independent of each other.


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


In [59]:
# It is often useful to use one ndarray to make slices, select, or change elements in another ndarray. 
# Let's see some examples:

# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print X
print()
print('X = \n', X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

# We print Y
print()
print('Y = \n', Y)

# We print Z
print()
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]


Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


### Diagonal
NumPy also offers built-in functions to select specific elements within ndarrays. 
For example, the np.diag(ndarray, k=N) function extracts the elements along the diagonal 
defined by N. As default is k=0, which refers to the main diagonal. Values of k > 0 are used to select 
elements in diagonals above the main diagonal, 
and values of k < 0 are used to select elements in diagonals below the main diagonal. Let's see an example:

In [60]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('X = \n', X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 1  7 13 19]

w =  [ 5 11 17 23]


### Unique value
It is often useful to extract only the unique elements in an ndarray. We can find the unique elements in an ndarray by using the np.unique() function. 
The np.unique(ndarray) function returns the unique elements in the given ndarray, as in the example below:

In [62]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X
print()
print('X = \n', X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]


### Boolean Indexing

Using logical arguments instead of explicit indices.


In [63]:
X = np.arange(25).reshape(5,5)
print(X)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [65]:
print(X[X>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [70]:
print(X[(X > 3) & (X < 19)])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [72]:
X[(X > 3) & (X < 19)] = -1
print(X)

[[ 0  1  2  3 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 19]
 [20 21 22 23 24]]


In [73]:
'''In addition to Boolean Indexing NumPy also allows for set operations. 
This useful when comparing ndarrays, for example, to find common elements between two ndarrays. 
Let's see some examples:
'''

# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


We can also sort ndarrays in NumPy. 
We will learn how to use the np.sort() function to sort rank 1 and rank 2 ndarrays in different ways. 
Like with other functions we saw before, the sort function can also be used as a method. 
However, there is a big difference on how the data is stored in memory in this case. When np.sort() is used as a function, it sorts the ndrrays out of place, meaning, that it doesn't change the original ndarray being sorted. However, when you use sort as a method, ndarray.sort() sorts the ndarray in place, meaning, that the original array will be changed to the sorted one. 
Let's see some examples:

In [75]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [8 9 4 4 5 4 8 1 1 3]

Sorted x (out of place): [1 1 3 4 4 4 5 8 8 9]

x after sorting: [8 9 4 4 5 4 8 1 1 3]


In [ ]:
Notice that np.sort() sorts the array but, 
if the ndarray being sorted has repeated values, np.sort() leaves those values in the sorted array. 
However, if desired, we can sort only the unique elements in x by combining the sort function with the unique function. 
Let's see how we can sort the unique elements of x above:

In [76]:
# We sort x but only keep the unique elements in x
print(np.sort(np.unique(x)))

[1 3 4 5 8 9]


Finally, let's see how we can sort ndarrays in place, by using sort as a method:

In [81]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


# When sorting rank 2 ndarrays, we need to specify to the np.sort() function whether we are sorting by rows or columns. This is done by using the axis keyword. Let's see some examples:

# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original x =  [6 4 5 3 7 9 2 7 8 8]

x after sorting: [2 3 4 5 6 7 7 8 8 9]

Original X = 
 [[ 8  6  5  5 10]
 [ 4  2  3 10  4]
 [ 9  2  4  2 10]
 [ 1  2 10  2  2]
 [ 2  2  8  4  5]]


X with sorted columns :
 [[ 1  2  3  2  2]
 [ 2  2  4  2  4]
 [ 4  2  5  4  5]
 [ 8  2  8  5 10]
 [ 9  6 10 10 10]]

X with sorted rows :
 [[ 5  5  6  8 10]
 [ 2  3  4  4 10]
 [ 2  2  4  9 10]
 [ 1  2  2  2 10]
 [ 2  2  4  5  8]]


### Arithmetic operations

We'll focus on element wise operations. We can use symbols and fuctions. Functions we can usually tweak to make it more flexible. 

We can use broadcasting. Use of arrays in different shapes. I-e either arrays are either same shape or be broadcastable.



In [83]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))

# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We can also apply mathematical functions, such as sqrt(x), to all elements of an ndarray at once.
# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2

# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()


# Another great feature of NumPy is that it has a wide variety of statistical functions. 
# Statistical functions provide us with statistical information about the elements in an ndarray. 

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

# Finally, let's see how NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)

# In the examples above, NumPy is working behind the scenes to broadcast 3 along the ndarray so that they have the same shape. 
# This allows us to add 3 to each element of X with just one line of code.

# Subject to certain constraints, 
# Numpy can do the same for two ndarrays of different shapes, as we can see below.

# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]

X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

x =  [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]

X = 
 [[1 2]
 [3 4]]

Average of all elements 